# Generated by Django 3.2.5 on 2021-08-21 17:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salescontact',
            name='group',
        ),
        migrations.RemoveField(
            model_name='staffcontact',
            name='group',
        ),
        migrations.RemoveField(
            model_name='supportcontact',
            name='group',
        ),
    ]
