# Generated by Django 3.2.5 on 2021-08-01 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salescontact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='staffcontact',
            options={},
        ),
        migrations.AlterModelOptions(
            name='supportcontact',
            options={},
        ),
        migrations.AlterField(
            model_name='contract',
            name='payment_due',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 16, 41, 14, 192167)),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 1, 16, 41, 14, 192984)),
        ),
        migrations.AlterModelTable(
            name='salescontact',
            table='SalesContacts',
        ),
        migrations.AlterModelTable(
            name='staffcontact',
            table='StaffContacts',
        ),
        migrations.AlterModelTable(
            name='supportcontact',
            table='SupportContacts',
        ),
    ]
