# Generated by Django 3.2.5 on 2021-08-21 16:13

from django.db import migrations


class Migration(migrations.Migration):

    def load_group_from_sql():
        from crm.settings import BASE_DIR
        import os
        sql_statements = open(os.path.join(BASE_DIR,'auth/sql/group.sql'), 'r').read()
        return sql_statements

    def delete_group_with_sql():
        return 'DELETE from auth_group;'

    def load_group_permissions_from_sql():
        from crm.settings import BASE_DIR
        import os
        sql_statements = open(os.path.join(BASE_DIR,'auth/sql/group_permissions.sql'), 'r').read()
        return sql_statements

    def delete_group_permissions_with_sql():
        return 'DELETE from auth_group_permissions;'

    def load_permission_from_sql():
        from crm.settings import BASE_DIR
        import os
        sql_statements = open(os.path.join(BASE_DIR,'auth/sql/permission.sql'), 'r').read()
        return sql_statements

    def delete_permission_with_sql():
        return "DELETE from auth_permission WHERE name = 'Can change contract status' and codename = 'change_contract_status';"

    dependencies = [
        ('crm_api', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(load_group_from_sql(), delete_group_with_sql()),
        migrations.RunSQL(load_permission_from_sql(), delete_permission_with_sql()),
        migrations.RunSQL(load_group_permissions_from_sql(), delete_group_permissions_with_sql()),
    ]
